name: axionym_guard
description: Mobile application for personal cybersecurity.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.3.1 # Added for anonymous technical auth
  firebase_app_check: ^0.3.1+4

  # UI & Utils
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  fl_chart: ^0.69.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
